#import "utils.typ":*

//set default text font and style
#set text(font: font_zh.SongTi, size: font_size_zh.XiaoSi)
#set par(leading: 12pt, first-line-indent: 0em, justify: true)

//set equation props
#set math.equation(numbering: "(1)", supplement: "")
#show figure.caption: set text(font:font_zh.SongTi, size: font_size_zh.WuHao)
#show figure.where(kind:image): set figure(supplement: "图") 
#show figure.where(kind:table): set figure(supplement: "表") 
#show figure.where(kind:table): set figure.caption(position:top)
#set pagebreak(weak: true)

#set page(footer: none)
#set heading(numbering: "1.1")
#include "preface.typ"
#outline(title: [#h(7.6cm)目录], depth: 2, indent: true)
#pagebreak(weak: true)

//page style
#set page(
  footer: [
    #set align(center)
    #counter(page).display("1")
  ]
)

//bib upercase style; disable autogenerated footnote
#set footnote(numbering: "[1]")
#set footnote.entry(separator: none)
#show footnote.entry: hide

#{counter(page).update(1)}

#Section[设计概述]
#SubSection[设计目的]
#MYPAR() 2048是一款著名的益智小游戏。其设计简单, 且易于得到较好的输出效果。
本作业设计2048小游戏, 并按要求实现提示模式, 以期锻炼编程本领, 实践程序设计知识。
#SubSection[设计内容]
#MYPAR()设计内容包含如下几个方面:
+ *2048小游戏规则* : 2048小游戏主要组成部分为4*4的方格阵列, 
方格为空或显示2, ..., 2048之一的数值; 游戏的主要流程为用户通过按方向键, 
使方格按移动方向依次尝试与该方向相邻方格合并(如果方格与相邻方格未发生合并且代表的值相同则进行合并。每进行一次移动后, 尝试在空方格生成2个值为2或4的方格, 空方格为一个时将其值改变为2或4); 
游戏的结束判定为: 方格阵不能发生改变则为失败、出现值为2048的方格则为胜利。
+ *提示模式* : 用户按下Ctrl+H请求提示, 此时方格进行一次合并, 以尽可能达到游戏胜利。
+ *用户得分记录* : 作业参考#link("")[Minesweeper Arbiter] 以游戏用时作为用户得分, 
最短用时为该用户的纪录; 作业同时实现用户注册、登录。
#SubSection[应用平台]
#MYPAR() 本程序实现在Windows11下进行搭建和测试, 理论上可以在任何支持Python和具有tty功能
(即支持ANSI转义序列渲染)的平台上运行。
#SubSection[开发工具]
+ *编译器* Python 3.11
+ *程序编辑器* VSCode(最新版本, 插件pylancer, python 等)
+ *终端* PowerShell(最新版本)
#SubSection[软件库]
#MYPAR()  使用的Python库包括:
#{
  set align(center)
  table(
    align: center,
    stroke: none,
    columns: (3cm,4cm,6.5cm),
    table.hline(y:0, stroke: 1pt),
    table.hline(y:1, stroke: 0.5pt),
    table.hline(y:7, stroke: 1pt),
    [库名称],[版本],[简介],
    [numpy],[],[实现常见的数学运算],
    [pynput],[],[实现跨平台兼容的键盘监听],
    [queue],[(内置库)],[实现跨线程通信],
    [time],[(内置库)],[获取当前时间],
    [json],[(内置库)],[配置信息存取],
    [os,sys],[(内置库)],[包含多种系统功能],
  )
}

#Section[详细设计]
#SubSection[总体方案]

#MYPAR() 程序实现前后端分离的结构, 有利于实现实时交互和向图形界面的扩展。程序结构如 @fig_struct 所示。

#figure(
  image("../img/the_structure.svg", height: 5cm),
  caption: [程序结构示意图]
)<fig_struct>

#MYPAR() 程序的主要组成部分为:

+ backend_worker: 实现了2048游戏的逻辑, 用时记录, 用户信息存储等, 设置并更新游戏状态。
+ on_press: 作为keyboard.Listener的调用函数, 处理键盘事件, 对方向键消息发送至backend_worker, 同时处理快捷键Ctrl+C和Ctrl+Q。
+ frontend_worker: 根据backend_worker的结果渲染命令行界面; 作为主循环决定是否运行, 同时根据命令行参数配置用户。
+ actions_queue, ack_queue: 内置库queue的实例, 负责在各部分间传递消息。


#SubSection[功能实现]

#Section[完成情况]
#SubSection[程序运行结果]
#SubSection[程序使用说明]
#SubSection[主要研究过程]

 #Section[设计总结]
 #SubSection[存在的问题]
 #SubSection[改进措施]
 #SubSection[课程收获]
 #SubSection[课程建议]


#SubSection[程序功能]

#MYPAR() 在除了实现2048小游戏基本逻辑以外, 程序还实现以下功能:
+ *提示模式*: 在用户启动游戏后, 输入Ctrl+H进入提示模式(即作弊模式)。提示模式下以最大合并数量为目标进行一次自动移动操作。一次游戏中提示模式不可改回正常模式, 以"(CHEATED)"字样进行标识, 游戏结束后不计入得分。
+ *用户信息*: 游戏支持多用户记录, 以命令行启动参数的第1、2项作为用户名和密码, 尝试注册或登录。默认用户和密码均为空字符串。
+ *计时和得分*: 游戏实时显示一次游戏从开始经历的时间, 以从开始到胜利的用时作为得分, 以最短用时作为当前用户的记录。
+ *界面渲染*: 游戏利用ANSI转义序列实现命令行覆写和彩色输出, 打印文本进行类GUI渲染。同时游戏根据窗口大小实时调整, 使界面尽可能居中。
+ *其他*: 游戏界面显示简短的操作说明。用户按Ctrl+C退出, 按Ctrl+Q打开#text(fill: aqua)[#link("https://github.com/lyn12233")[网页说明]]。





#Section[程序实现]
#SubSection[程序结构]




#SubSection[运行流程]

#MYPAR() 程序实现了3个游戏状态(state): 停止状态(pending)、运行状态(playing)和提示状态(cheated)。程序启动时为停止状态, 在停止状态下通过按方向键进入运行状态。运行状态下通过提示(Ctrl+H)进入提示状态。满足结束条件后回到停止状态。

#Section[程序说明]

#SubSection[依赖库]
#MYPAR()第三方依赖库为numpy, pynput, 运行 #box(fill: luma(235), outset: 3pt)[#raw("pip install -r requirements.txt")] 安装。

#SubSection[运行方法]
#MYPAR()可以通过如下指令运行此程序。

#align(center)[
#block(fill: luma(235), width: 16cm, outset: 3pt)[
#set align(left)
#raw("cd path/to/game/folder\npython . [<user_name>] [<password>]",lang:"bash", align: center)]]

#MYPAR() 也可以通过执行 #box(fill:luma(235), outset: 3pt,)[#raw("__main__.py")] 运行此程序。

#SubSection[常量说明]
#MYPAR()在config.py中定义了以下常量, 以便调试和演示:
+ N: 含N*N的方格。N通常为4。
+ LVWIN: 方格的值出现 $2^("LVWIN")$ 判定为胜利。降低LVWIN可方便调试。游戏时应为11。

#Section[程序演示]

#figure(
  image("../img/on_start.png", height: 10cm),
  caption: [启动界面, 方格样式的展示]
)
#figure(
  image("../img/finish_anonymous.png", height: 10cm),
  caption: [胜利结算画面(默认用户)]
)
#figure(
  image("../img/new_record.png", height: 10cm),
  caption: [胜利结算画面(名为user1的用户, 新纪录)]
)
#figure(
  image("../img/cheating.png", height: 10cm),
  caption: [提示模式]
)
#figure(
  image("../img/fail.png", height: 10cm),
  caption: [失败结算画面]
)
#figure(
  image("../img/finish_cheated.png", height: 10cm),
  caption: [提示模式下胜利]
)

#Section[评价与推广]

#SubSection[本程序的优点]
+ 100%完成了作业要求。
+ 实现了彩色渲染、计时器等额外功能。

#SubSection[本程序的缺点]
#v(6pt)
+ 提示模式不够智能。
+ 一定环境下程序退出时不能恢复原有颜色样式。

#SubSection[程序的推广]
#MYPAR() 可以利用wx、qt等图形界面库重写前端部分, 做出更为惊艳的实现。

#Section[参考资料]

[1] python+tkinter实现: #link("https://github.com/yangshun/2048-python")

[2] cpp命令行实现: #link("https://github.com/plibither8/2048.cpp")